SET foreign_key_checks = 0;

DROP TABLE IF EXISTS
`#__thm_groups_abstract_attributes`,
`#__thm_groups_additional_userdata`,
`#__thm_groups_associations`,
`#__thm_groups_attribute`,
`#__thm_groups_attributes`,
`#__thm_groups_categories`,
`#__thm_groups_conf`,
`#__thm_groups_content`,
`#__thm_groups_date`,
`#__thm_groups_dynamic_type`,
`#__thm_groups_field_types`,
`#__thm_groups_groups`,
`#__thm_groups_group_map`,
`#__thm_groups_link`,
`#__thm_groups_multiselect`,
`#__thm_groups_multiselect_extra`,
`#__thm_groups_number`,
`#__thm_groups_picture`,
`#__thm_groups_picture_extra`,
`#__thm_groups_profile_associations`,
`#__thm_groups_profile_attribute`,
`#__thm_groups_profile_attributes`,
`#__thm_groups_profile_usergroups`,
`#__thm_groups_profiles`,
`#__thm_groups_publishrelation`,
`#__thm_groups_relationtable`,
`#__thm_groups_role_associations`,
`#__thm_groups_roles`,
`#__thm_groups_settings`,
`#__thm_groups_static_type`,
`#__thm_groups_structure`,
`#__thm_groups_table`,
`#__thm_groups_table_extra`,
`#__thm_groups_template_associations`,
`#__thm_groups_template_attributes`,
`#__thm_groups_templates`,
`#__thm_groups_text`,
`#__thm_groups_text_extra`,
`#__thm_groups_textfield`,
`#__thm_groups_textfield_extra`,
`#__thm_groups_usergroups_roles`,
`#__thm_groups_users`,
`#__thm_groups_users_attribute`,
`#__thm_groups_users_categories`,
`#__thm_groups_users_content`,
`#__thm_groups_users_profile`,
`#__thm_groups_users_usergroups_moderator`,
`#__thm_groups_users_usergroups_roles`,
`#__thm_quickpages_featured`,
`#__thm_quickpages_map`;

SET foreign_key_checks = 1;