DROP TABLE IF EXISTS `#__thm_groups_text_extra`,
					 `#__thm_groups_textfield_extra`,
					 `#__thm_groups_textfield`,
					 `#__thm_groups_text`,
					 `#__thm_groups_table_extra`,
					 `#__thm_groups_table`,
					 `#__thm_groups_structure`,
					 `#__thm_groups_roles`,
					 `#__thm_groups_relationtable`,
					 `#__thm_groups_publishrelation`,
					 `#__thm_groups_picture`,
					 `#__thm_groups_picture_extra`,
					 `#__thm_groups_number`,
					 `#__thm_groups_multiselect_extra`,
					 `#__thm_groups_multiselect`,
					 `#__thm_groups_link`,
					 `#__thm_groups_groups_map`,
					 `#__thm_groups_groups`,
					 `#__thm_groups_date`,
					 `#__thm_groups_conf`,
					 `#__thm_groups_additional_userdata`,
					 `#__thm_quickpages_map`,
					 `#__thm_groups_static_type`,
					 `#__thm_groups_dynamic_type`,
					 `#__thm_groups_structure_item`;

